// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1KrhL7O4Bz9zd9T9cFagd5L9ZbIq5ABU',
    appId: '1:12758654380:web:eef4eb60c79c4f7d222e09',
    messagingSenderId: '12758654380',
    projectId: 'prayer-times-lk',
    authDomain: 'prayer-times-lk.firebaseapp.com',
    storageBucket: 'prayer-times-lk.appspot.com',
    measurementId: 'G-DM6W907Q5W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNHyOCrsLZt6KeP6s6T5aDmkZJxv3JZgA',
    appId: '1:12758654380:android:f1e912bdb4379089222e09',
    messagingSenderId: '12758654380',
    projectId: 'prayer-times-lk',
    storageBucket: 'prayer-times-lk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTi14rA1O_Df5TGpcPRX4IWgUrwE7-wVA',
    appId: '1:12758654380:ios:0a81783344c9d12f222e09',
    messagingSenderId: '12758654380',
    projectId: 'prayer-times-lk',
    storageBucket: 'prayer-times-lk.appspot.com',
    iosBundleId: 'com.ali.prayerTime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTi14rA1O_Df5TGpcPRX4IWgUrwE7-wVA',
    appId: '1:12758654380:ios:0a81783344c9d12f222e09',
    messagingSenderId: '12758654380',
    projectId: 'prayer-times-lk',
    storageBucket: 'prayer-times-lk.appspot.com',
    iosBundleId: 'com.ali.prayerTime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1KrhL7O4Bz9zd9T9cFagd5L9ZbIq5ABU',
    appId: '1:12758654380:web:06db5e153c6da9f0222e09',
    messagingSenderId: '12758654380',
    projectId: 'prayer-times-lk',
    authDomain: 'prayer-times-lk.firebaseapp.com',
    storageBucket: 'prayer-times-lk.appspot.com',
    measurementId: 'G-GY9W80EYQH',
  );
}
